// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/HunterGooD/go_test_task/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// SongUsecase is an autogenerated mock type for the SongUsecase type
type SongUsecase struct {
	mock.Mock
}

// GetListSong provides a mock function with given fields: ctx, filters
func (_m *SongUsecase) GetListSong(ctx context.Context, filters map[string]string) ([]entity.Song, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetListSong")
	}

	var r0 []entity.Song
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) ([]entity.Song, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []entity.Song); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Song)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSongUsecase creates a new instance of SongUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSongUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SongUsecase {
	mock := &SongUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
